import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  await knex("cat_superheroes").del();

  await knex("cat_superheroes").insert([
    {
      nombre_heroe: "Spider-Man",
      nombre_real: "Peter Parker",
      universo: "Marvel",
      poder_principal: "Sentido aracnido y agilidad sobrehumana",
      fortaleza: "Su reflejo y sentido aracnido",
      resistencia: "Alta",
      debilidad: "Ondas sonicas de alta frecuencia",
      imagen_url: "Spider-Man.png",
    },
    {
      nombre_heroe: "Batman",
      nombre_real: "Bruce Wayne",
      universo: "DC",
      poder_principal: "Estrategia, tecnologia y combate",
      fortaleza: "Disciplina y preparacion",
      resistencia: "Humana maxima",
      debilidad: "Mortalidad",
      imagen_url: "Batman.png",
    },
    {
      nombre_heroe: "Wonder Woman",
      nombre_real: "Diana Prince",
      universo: "DC",
      poder_principal: "Fuerza y resistencia sobrenaturales",
      fortaleza: "Entrenamiento amazonico",
      resistencia: "Muy alta",
      debilidad: "Vulnerable a armas perforantes",
      imagen_url: "Wonder-Woman.png",
    },
    {
      nombre_heroe: "Superman",
      nombre_real: "Clark Kent",
      universo: "DC",
      poder_principal: "Vuelo, super fuerza y vision de calor",
      fortaleza: "Sol amarillo",
      resistencia: "Extremadamente alta",
      debilidad: "Kryptonita",
      imagen_url: "Superman.png",
    },
    {
      nombre_heroe: "Flash",
      nombre_real: "Barry Allen",
      universo: "DC",
      poder_principal: "Super velocidad y capacidad de vibrar",
      fortaleza: "La Speed Force",
      resistencia: "Acelerada",
      debilidad: "Frio extremo",
      imagen_url: "Flash.png",
    },
    {
      nombre_heroe: "Iron Man",
      nombre_real: "Tony Stark",
      universo: "Marvel",
      poder_principal: "Genio multimillonario y armadura avanzada",
      fortaleza: "Su inteligencia y recursos",
      resistencia: "La de su armadura",
      debilidad: "Su ego y dependencia de la armadura",
      imagen_url: "Ironman.png",
    },
    {
      nombre_heroe: "Captain America",
      nombre_real: "Steve Rogers",
      universo: "Marvel",
      poder_principal: "Fuerza y agilidad mejoradas, escudo indestructible",
      fortaleza: "Su voluntad inquebrantable",
      resistencia: "Maxima humana",
      debilidad: "Su sentido del deber",
      imagen_url: "Placeholder.png",
    },
    {
      nombre_heroe: "Thor",
      nombre_real: "Thor Odinson",
      universo: "Marvel",
      poder_principal: "Control del trueno y Mjolnir",
      fortaleza: "Dios del trueno",
      resistencia: "Asgardiana",
      debilidad: "Su arrogancia",
      imagen_url: "Placeholder.png",
    },
    {
      nombre_heroe: "Black Widow",
      nombre_real: "Natasha Romanoff",
      universo: "Marvel",
      poder_principal: "Maestra en combate y espionaje",
      fortaleza: "Entrenamiento extremo",
      resistencia: "Humana elite",
      debilidad: "Mortalidad",
      imagen_url: "Placeholder.png",
    },
    {
      nombre_heroe: "Aquaman",
      nombre_real: "Arthur Curry",
      universo: "DC",
      poder_principal: "Control del agua y comunicacion marina",
      fortaleza: "Rey de Atlantis",
      resistencia: "Sobrehumana bajo el agua",
      debilidad: "Dependencia del agua",
      imagen_url: "Placeholder.png",
    },
    {
      nombre_heroe: "Hulk",
      nombre_real: "Bruce Banner",
      universo: "Marvel",
      poder_principal: "Fuerza ilimitada al transformarse",
      fortaleza: "Su ira",
      resistencia: "Casi invulnerable",
      debilidad: "Control de su ira",
      imagen_url: "Placeholder.png",
    },
    {
      nombre_heroe: "Green Lantern",
      nombre_real: "Hal Jordan",
      universo: "DC",
      poder_principal: "Anillo de poder que materializa construcciones",
      fortaleza: "Fuerza de voluntad",
      resistencia: "Depende del anillo",
      debilidad: "Color amarillo",
      imagen_url: "Placeholder.png",
    },
  ]);
}
